### ISSUE TITLE
AGP version downgrade(7.4.1) 해서 빌드할 경우 Backend Internal error: Exception during IR lowering

### ISSUE THREAD

**Issue by easyhooon** [daryeou/kakao-assignment#1]
맥환경에서 AGP version 8.0.0 이상으로 빌드할 경우 빌드가 불가능하여 7.4.0 or 7.4.1 로 downgrade 한 뒤에 빌드하면 
다음과 같은 에러가 발생합니다.

org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /Users/yijihun/AndroidStudioProjects/kakao-assignment/app/src/main/java/com/daryeou/app/navigation/KakaoNavHost.kt
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:49)... 이하 생략 

관련해서 이슈를 찾아보았고
https://youtrack.jetbrains.com/issue/KT-51661
https://issuetracker.google.com/issues/221280935
해결 방법으로 제시한 clean/rebuild 를 해보았으나 같은 에러가 발생해 빌드를 실패했습니다

**Comment by daryeou** [comment]
AGP 버전을 7.4.1로 변경하였으며, gradle 관련하여 일부 코드가 누락되어 추가하였습니다.

**Comment by easyhooon** [comment]
변경 사항 pull 하여 정상적으로 빌드 되는 것을 확인했습니다!
